### ISSUE TITLE
Code blocks broken

### ISSUE THREAD

**Issue by bondz** [code-hike/v1#1]
Take any of the examples on codesandbox and add a codeblock like

````
```js
'use anything';
```
````

The page would error.

I think now that there's a dedicated `Hike` component to use in markdown, the user should be allowed to opt in to using codehike to parse regular code blocks.

**Comment by pomber** [comment]
You are adding the codeblock inside or outside a Hike?

**Comment by bondz** [comment]
Outside the Hike component

**Comment by pomber** [comment]
Yes, currently it assumes there's a `Code` component defined in `./mdx-components.tsx`. 

The idea is to make this configurable in the mdx configuration:


```js
const chConfig = {
  parseAllCodeblocksOrSomething: true | false,
}

const withMDX = nextMDX({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [[remarkCodeHike, chConfig]],
    recmaPlugins: [recmaCodeHike, chConfig]],
    jsx: true,
  },
})
```

not sure of the name though, any suggestions?

**Comment by bondz** [comment]
There's already a `skipLanguages` option, this could be `skipCodeBlocks` perhaps. Or, `parseOnlyHikeComponents` or similar.

**Comment by pomber** [comment]
codeblocks are opt-in now https://v1.codehike.org/docs/concepts/code
